### ISSUE TITLE
Find a good reference for what constitutes a learning objective

### ISSUE THREAD

**Issue by katyhuff** [necx-org/nodes#25]
Find a good reference for what constitutes a learning objective. Include it in the guidance for contributors and reviewers.

**Comment by TheDoctorRAB** [comment]
As subject matter experts in their field, faculty know almost intuitively what the most important things are that students must master. In order to develop learning goals, faculty should answer the question, “What do I want my students to know or be able to do by the end of this course?”

http://teaching.berkeley.edu/resources/design/course-level-learning-goalsoutcomes

**Comment by jennyamos** [comment]
Each objective should be specific, actionable, and observable (meaning you can somehow see it and record the event). 
I teach this quite often and explain it as focusing on the verbs and nouns, verbs from Blooms and nouns from your discipline.  Any student who takes your class or learns this "thing" should know how to VERB NOUN and if they can VERB NOUN then they know it. I.e. Student will be able to derive Fick's Law.  
Blooms verbs: http://www.fresnostate.edu/academics/oie/documents/assesments/Blooms%20Level.pdf
This is a good resource: https://provost.illinois.edu/assessment/learning-outcomes-assessment/what-is-learning-outcomes-assessment/

**Comment by katyhuff** [comment]
Links to these now exist in the CONTRIBUTING.md doc.
